GET http://localhost:3000/marcas
###
GET http://localhost:3000/marcas/1
###
DELETE http://localhost:3000/marcas/1

###
//Produtos
GET http://localhost:3000/produtos
###
GET http://localhost:3000/produtos/1
###
POST http://localhost:3000/produtos

###
//Clientes
GET http://localhost:3000/clientes
###
GET http://localhost:3000/clientes/1
###
POST http://localhost:3000/clientes

###
//Pedidos
GET http://localhost:3000/pedidos
###
GET http://localhost:3000/pedidos/1
###
GET http://localhost:3000/pedidos/cidade/Cataguases
###
POST http://localhost:3000/pedidos
